#!/usr/bin/env bash

function main {
  local shome="${_rbtools_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ "$(rbt --version 2>&1 | head -1 | awk '{print $2}')" == "0.7.4" ]]; then
    return 1
  fi

  return 0
}

source sub "$BASH_SOURCE" "$@"
